### ISSUE TITLE
为什么不给作者提PR？

### ISSUE THREAD

**Issue by ikarosu** [Hokorizero/EBW-Simplified-Chinese-Translation#59]
是作者不接受吗？

**Comment by TUsama** [comment]
不，这里大概只是个中转站，如果直接在fork出来的官库施工，容易产生大量的commit，这样会很丑，所以我们是把文件放在独立的仓库进行翻译，最后只给作者提供一个commit，这样很简练。

**Comment by WuzgXY-GitHub** [comment]
> 最后只给作者提供一个commit

我可不觉得丑 ..(:з」∠)..
