### ISSUE TITLE
您好，关于am3翻译撞车一事

### ISSUE THREAD

**Issue by ahdg6** [Hokorizero/EBW-Simplified-Chinese-Translation#66]
您好，见下文

**Comment by ahdg6** [comment]
我观察到你们的pr已经完成了，如果不是你们改了mcmod的相关页我们也不知道你们在进行相同的工作

**Comment by ahdg6** [comment]
对于撞车的问题我感到很遗憾，但图书部分内容我们进度并没有比你们快，所以我认为最好将pr放到库里，以便我们对相关内容进行改进并统一翻译名词

**Comment by ahdg6** [comment]
我们注意到部分名词和AM过往版本并不统一，鉴于我们的翻译工作陆陆续续进行了十天，做的精翻，对mod的过往版本有较深的了解，我期待你们对我方相关请求的回复，并给予一个合适的解决方案

**Comment by TUsama** [comment]
严格来说我在7月25号就已经进行了翻译工作，期间屡次想在mcmod主页上贴地址，但是最终还是决定不贴了，今天这个是因为发现那个译名，我才意识到有人可能也在翻译，所以我就贴了出来。

我不排斥多人协作，尤其是GitHub这个平台本身就是多人协作的平台。如果你已经有了一个存放am3的仓库，那么你可以贴出来，我会帮忙看一看。如果没有的话，我可以在这边拉一个仓库出来单独存放，这样子方便管理。

**Comment by ahdg6** [comment]
很高兴你对撞车这件事没有抵触，我们的译文并不存储在github，我目前的想法就是既然你翻译比我们早那么多，我们打算在你的译文上面进行改进，但是我们目前的进度与你大部分是冲突的，相关译词也不一，github来进行交流也不方便，请问您还有别的联系方式吗？

**Comment by TUsama** [comment]
qq 1716976420
