### ISSUE TITLE
关于巫师手册有乱码和失效图片

### ISSUE THREAD

**Issue by Phenonium** [Hokorizero/EBW-Simplified-Chinese-Translation#70]
您好。

我在尝试游玩巫术学mod（4.3.4）的时候，发现您目前提供的材质包存在乱码和图片链接失效的问题。我顺手转了个码调整了一下链接，您检查如果可用的话，不妨在program里更新一下。

祝好。

[handbook_zh_cn.zip](https://github.com/LWHK/LWHK-Simplified-Chinese-Translation/files/6396707/handbook_zh_cn.zip)

**Comment by TUsama** [comment]
是自动汉化那边的问题，我已经修了，删掉下载的资源包，重新下载即可。

**Comment by TUsama** [comment]
还有，4.3版本之后并不需要额外的资源包，直接游玩即可。
